<?php

/**
 * @file
 * Greenhouse Job Board API module hooks.
 */

use Drupal\gh_jobs\GhJobsInterface;

/**
 * Implements hook_theme().
 */
function gh_jobs_theme($existing, $type, $theme, $path) {
  return [
    'gh_jobs__career_page' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'gh_jobs__career_list' => [
      'variables' => [
        'jobs' => NULL,
      ],
    ],
    'gh_jobs__career_item_list' => [
      'variables' => [
        'job' => NULL,
        'link' => NULL,
      ],
    ],
    'gh_jobs__job_details' => [
      'variables' => [
        'job' => NULL,
        'content' => NULL,
        'departments' => NULL,
        'offices' => NULL,
        'link' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_library_info_build().
 */
function gh_jobs_library_info_build() {
  $configs = \Drupal::configFactory()->get(GhJobsInterface::GH_JOBS_SETTINGS);
  $board = $configs->get(GhJobsInterface::BOARD_TOKEN_CONFIG_NAME);

  $libraries = [];
  $libraries['embed_gh_board_scrip'] = [
    'js' => [
      GhJobsInterface::GH_SCRIPT_URL . $board => ['type' => 'external'],
      'js/apply.js' => [],
    ],
    'dependencies' => [
      'core/jquery',
      'core/drupalSettings',
    ],
  ];

  return $libraries;
}
