<?php

/**
 * @file
 * Greenhouse Job Board API module hooks.
 */

/**
 * Config settings.
 *
 * @var string
 */
const GH_JOBS_SETTINGS = 'gh_jobs.settings';

/**
 * APIKey config name.
 *
 * @var string
 */
const API_KEY_CONFIG_NAME = 'api_key';

/**
 * Board Token config name.
 *
 * @var string
 */
const BOARD_TOKEN_CONFIG_NAME = 'board_token';

/**
 * Jobs list cache CID.
 *
 * @var string
 */
const JOBS_CACHE_CID = 'gh_jobs.cached_list';

/**
 * Jobs item cache CID.
 *
 * @var string
 */
const JOB_CACHE_CID = 'gh_jobs.cached_job';

/**
 * Greenhouse embed board script URL.
 *
 * @var string
 */
const GH_SCRIPT_URL = 'https://app.greenhouse.io/embed/job_board/js?for=';

/**
 * Implements hook_theme().
 */
function gh_jobs_theme($existing, $type, $theme, $path) {
  return [
    'gh_jobs__career_page' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'gh_jobs__career_list' => [
      'variables' => [
        'jobs' => NULL,
      ],
    ],
    'gh_jobs__career_item_list' => [
      'variables' => [
        'job' => NULL,
        'link' => NULL,
      ],
    ],
    'gh_jobs__job_details' => [
      'variables' => [
        'job' => NULL,
        'content' => NULL,
        'departments' => NULL,
        'offices' => NULL,
        'link' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_library_info_build().
 */
function gh_jobs_library_info_build() {
  $configs = \Drupal::configFactory()->get(GH_JOBS_SETTINGS);
  $board = $configs->get(BOARD_TOKEN_CONFIG_NAME);

  $libraries = [];
  $libraries['embed_gh_board_scrip'] = [
    'js' => [
      GH_SCRIPT_URL . $board => ['type' => 'external'],
      'js/apply.js' => [],
    ],
    'dependencies' => [
      'core/jquery',
      'core/drupalSettings',
    ],
  ];

  return $libraries;
}
