<?php

/**
 * @file
 * Greenhouse Job Migrate module hooks.
 */

/**
 * Implements hook_theme().
 */
function gh_jobs_migrate_theme($existing, $type, $theme, $path) {
  return [
    'gh_jobs_migrate__apply_block' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function gh_jobs_migrate_cron() {
  // Execute the Jobs migration service.
  \Drupal::service('gh_jobs.jobs_migrate_update')->execute();
}
